#!/usr/bin/with-contenv bash

echo "**** install packages ****" && \
  apk add --no-cache bash ffmpeg jq

[[ -f /config/nzbget.conf ]] && \
  source /config/nzbget.conf &>/dev/null

[[ -z "${ScriptDir}" ]] && \
  ScriptDir=/downloads/scripts

mkdir -p "${ScriptDir}"

cp /mp4.sh "${ScriptDir}/"
chown abc:abc -R "${ScriptDir}"
chmod +x "${SciptDir}/mp4.sh"
